#!/bin/bash
set -eu

WINDOWS="0800-1200 1300-1700 1800-2000 2030-2200"

SITES="
discord.com www.discord.com canary.discord.com ptb.discord.com discord.gg
discordapp.com www.discordapp.com cdn.discordapp.com discordapp.net
media.discordapp.net gateway.discord.gg discord.media
youtube.com www.youtube.com m.youtube.com music.youtube.com tv.youtube.com
studio.youtube.com youtu.be www.youtu.be youtubei.googleapis.com
ytimg.com i.ytimg.com s.ytimg.com
twitter.com www.twitter.com mobile.twitter.com api.twitter.com
x.com www.x.com mobile.x.com api.x.com t.co
twimg.com pbs.twimg.com abs.twimg.com video.twimg.com
"

t=$((10#${FOCUS_NOW:-$(date +%H%M)}))
on=0
for w in $WINDOWS; do
	(( t >= 10#${w%-*} && t < 10#${w#*-} )) && on=1
done

if [ "${1:-}" = --dry ]; then
	(( on )) && echo on || echo off
	exit 0
fi

sed -i '/#focus-block$/d' /etc/hosts
if (( on )); then
	for h in $SITES; do
		printf '127.0.0.1 %s #focus-block\n::1 %s #focus-block\n' "$h" "$h"
	done >> /etc/hosts
fi
